_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: es
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  auto_entitylabel: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  config: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  go_back: 0
  help: 0
  image: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pwa: 0
  quickedit: 0
  rdf: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  tome: 0
  tome_base: 0
  tome_static: 0
  tome_sync: 0
  toolbar: 0
  tour: 0
  user: 0
  video_embed_field: 0
  views_field_formatter: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  install_profile: 1000
theme:
  stable: 0
  claro: 0
  gin: 0
  olivero: 0
profile: install_profile
